### ISSUE TITLE
iteratively increasing openai api usage?

### ISSUE THREAD

**Issue by klebs6** [llm-workflow-engine/llm-workflow-engine#325]
greetings! First off, thank you for providing this software! I appreciate your work!!

***Description of bug, steps to reproduce***

 I am not sure whether this is a bug in my config, a misunderstanding on my part, or a bug in lwe.

I had a conversation with gpt4 using the lwe command interface and thought everything was going well.  I held a conversation over the course of an hour or so that consisted of roughly 22 questions and answers.

Then, I got a message like this:

```
Conversation exceeded max submission tokens (8192), stripped out 5 oldest messages before sending, sent 8171 tokens instead

```

The gpt4 response was subsequently truncated.

My question was a one sentence prompt, consisting of ten English language words posed as a question.

***Expected Behavior***
I would not have expected the system to need to submit this many tokens for a single, simple prompt.  

I expect the number of tokens to be a function of the number of tokens in a single call and response.  Is this correct? I don't expect this value to depend on the size of the full conversation history, since the full conversation history increases linearly with the number of conversation steps.

I am wondering: is the full conversation is being submitted on every request?  Is this expected behavior?  On the openai dev platform, the bill looks like this:

<img width="367" alt="Screenshot 2023-08-19 at 2 27 21 AM" src="https://github.com/llm-workflow-engine/llm-workflow-engine/assets/92199902/aaa54c09-b1bf-4cd6-a788-87a179db3bee">

It looks like the number of tokens being sent on each request is always growing, even though my questions are all roughly the same length.

I realize it is possible this is a known and correct behavior -- it could be an aspect of how the openai systems have been designed to work.

However, I do remember using the chatgpt-wrapper program with gpt4 several months ago on a ChatGPT Plus subscription and encountering nothing like this.

the total bill was roughly 2 dollars -- this seems staggeringly high for a conversation consisting of 22 back and forth messages. Also, further steps in the conversation keep triggering this error about `stripping out the N oldest messages`

I have a ChatGPT plus subscription and can communicate with GPT4 in the browser as much as I like (minus the current system throttle behavior of 50 messages every few hours).

Using the command line interface is much better, if possible -- Is there a solution or workaround?

** Additional Context **

Here is my config:
```

klebs@gpt-4 26> /config
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                  Backend configuration: api                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                      File configuration                                                                      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

 • Config dir: /Users/kleb/Library/Application Support/llm-workflow-engine
 • Config profile dir: /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default
 • Config file: /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/config.yaml
 • Data dir: /Users/kleb/.local/share/llm-workflow-engine
 • Data profile dir: /Users/kleb/.local/share/llm-workflow-engine/profiles/default
 • Database: sqlite:////Users/kleb/.local/share/llm-workflow-engine/profiles/default/storage.db
 • Template dirs:
    • /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/templates
    • /Users/kleb/Library/Application Support/llm-workflow-engine/templates
 • Preset dirs:
    • /Users/kleb/Library/Application Support/llm-workflow-engine/presets
    • /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/presets
 • Workflow dirs:
    • /Users/kleb/Library/Application Support/llm-workflow-engine/workflows
    • /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/workflows
 • Function dirs:
    • /Users/kleb/Library/Application Support/llm-workflow-engine/functions
    • /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/functions

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                               Profile 'default' configuration:                                                               ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


 backend: api
 backend_options:
   default_conversation_id: null
   default_user: klebs
 chat:
   log:
     enabled: false
     filepath: lwe.log
 database: sqlite:////Users/kleb/.local/share/llm-workflow-engine/profiles/default/storage.db
 debug:
   log:
     enabled: false
     filepath: /tmp/lwe-debug.log
     format: '%(name)s - %(asctime)s - %(levelname)s - %(message)s'
     level: DEBUG
 directories:
   functions:
   - /Users/kleb/Library/Application Support/llm-workflow-engine/functions
   - /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/functions
   plugins:
   - /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/plugins
   - /Users/kleb/Library/Application Support/llm-workflow-engine/plugins
   presets:
   - /Users/kleb/Library/Application Support/llm-workflow-engine/presets
   - /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/presets
   templates:
   - /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/templates
   - /Users/kleb/Library/Application Support/llm-workflow-engine/templates
   workflows:
   - /Users/kleb/Library/Application Support/llm-workflow-engine/workflows
   - /Users/kleb/Library/Application Support/llm-workflow-engine/profiles/default/workflows
 log:
   console:
     format: '%(name)s - %(levelname)s - %(message)s'
     level: ERROR
 model:
   default_preset: null
   default_system_message: default
   streaming: true
   system_message:
     creative_writer: You are a creative writing assistant.
     default: You are a helpful assistant.
     programmer: You are an expert programmer, who responds to questions with brief
       examples in code. Our primary language is rust. Use advanced vocabulary as frequently
       as possible
 plugins:
   echo:
     response:
       prefix: Echo
   enabled:
   - echo
   - examples
   examples:
     confirm_overwrite: true
     default_types:
     - presets
     - templates
     - workflows
     - functions
   provider_chat_openai: {}
 shell:
   history_file: /tmp/repl_history.log
   prompt_prefix: '($TEMPERATURE/$MAX_SUBMISSION_TOKENS/$CURRENT_CONVERSATION_TOKENS):
     $SYSTEM_MESSAGE_ALIAS$NEWLINE$USER@$PRESET_OR_MODEL'
   streaming: true


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                    Runtime configuration                                                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

 • Streaming: True
 • Logging to: /tmp/gpt-log.txt
 • Max submission tokens: 8192
 • System message: You are a helpful assistant.

```

**Comment by thehunmonkgroup** [comment]
This is a misunderstanding of the way the model works. Models are 'stateless', similar to HTTP requests.

From https://platform.openai.com/docs/guides/gpt/chat-completions-api

> Because the models have no memory of past requests, all relevant information must be supplied as part of the conversation history in each request. If a conversation cannot fit within the model’s token limit, it will need to be [shortened](https://platform.openai.com/docs/guides/gpt-best-practices/tactic-for-dialogue-applications-that-require-very-long-conversations-summarize-or-filter-previous-dialogue) in some way.

If you're going to use the API, it *definitely* pays to study the documentation and understand both how it to interact with it, and what parameters are available to affect its behavior.

Your ability to have endless conversations with ChatGPT is just that app managing the conversation history for you. How it does that is internal to the app -- it could just be silently cutting off messages, or collecting older messages and rewriting them to a single summary message, or something else.

LWE provides you visibility into token consumption as a conversation progresses:

![2023-08-19_12-03](https://github.com/llm-workflow-engine/llm-workflow-engine/assets/43772/e38d9a40-4812-4c1a-859c-7e94e1467404)

The first number is the current 'temperature', the second number is the token limit of the current model (both input and output), and the third number is the total number of tokens in the current conversation's history.

In that example pictured above, if I were to simply send 'hello' as the next message, that request would consume approximately 2649 tokens (2648 to pass in the conversation history, 1 for the word 'hello')

This is an important thing to keep in mind if you care about cost. As you can see token consumption in a conversation is NOT linear. My limited mathematical understanding is that total token use in a conversation would progress more quadratically than linearly.

The worst thing to do if you care about cost is to have a lot of very long conversations. So in your example, when you kept continuing the conversation, and LWE kept truncating messages, *each turn* was costing you nearly 8000 tokens!

Let's look at that warning message you got as an example:

```
Conversation exceeded max submission tokens (8192), stripped out 5 oldest messages before sending, sent 8171 tokens instead
```

So to send that one question, however long it was, cost 8171 tokens for the input. The response from GPT-4 was cut off because there were almost no available tokens left in its context window for the response (8192 - 8171 = 21 tokens *approximately*).

So yes, with the ChatGPT app, ignorance is bliss. Not so with the API, you have to remain aware of usage, and how it works.

However, I can tell you that I ONLY use the API for conversion with GPT-4. I remain aware of conversation length, keep my individual conversations focused, summarize when necessary, etc. It's really not that hard once you understand how it operates. This last month I was even running some automated testing using GPT-4, and my bill was still under $40 for the month. And for that I have no message limits, and a HIGH degree of control over the model's output.

Hope this explanation helps.

**Comment by klebs6** [comment]
Thank you. 

I appreciate the quality of your explanation -- your answer made a big difference for me in terms of my understanding.  

Is it possible to use the `ChatGPT Plus` App instead of the API with lwe?

I am planning a series of many multi-hour long conversations with the gpt4.  

It seems like it will be much more cost effective for me to use their $20 per month, 50 messages per 3 hours access point.

Currently, the only way I know of to do this is within the browser.  Is it possible to do it with the command line?

**Comment by thehunmonkgroup** [comment]
> I am planning a series of multi-hour conversations with the gpt4.

My previous explanation was meant to highlight that this is an illusion. The context window is 8192 tokens for input plus output. When you get beyond that, you are *losing* context. Just because the ChatGPT app hides it from you does not mean it's not happening.

Two sides comments about my last claim:

1. It's theoretically possible the GPT-4 that the ChatGPT Plus app is using is their 32K context model, but that seems *extremely* unlikely.
2. It's also possible that you're satisfied with however the ChatGPT app is handling things when you go beyond the context window. But you also have to be OK not knowing what it's doing, or exactly what context you're losing and how.

My strong advice for you is to rethink what you're trying to accomplish now that you better understand the limitations you're working with.

> Is it possible to access the `ChatGPT Plus` Application via lwe?

See [here](https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/CHATGPT_WRAPPER.md)

There also may be other open source apps that wrap the ChatGPT app. Many of the original ones were broken by OpenAI's security changes, including, finally, ours. They don't want people programmatically accessing their web app -- it's probably against their terms of service, too.

**Comment by klebs6** [comment]
Thanks for this explanation -- it helped me understand much more deeply.
I appreciate your help  🌿🌿 All the best 😃
